### ISSUE TITLE
Set a default currency

### ISSUE THREAD

**Issue by fire015** [Dintero/money#182]
Feature request: can we have a way to set a default currency? We only use a single currency and it pains me to see the string "GBP" all over the codebase.

Either make the currency param optional (which defaults to unknown) or a global way of setting it.

Great library btw! Thanks :)

**Comment by frodeaa** [comment]
Requiring currency is by design, e.g. to safeguard mixing money of different currency

You can maybe solve it by creating a util function/class that set a default currency?

```ts
// gbp_money.ts
export class Money {
    static of(amount: NumberInput, options?: AdditionalOptions): Money {
        return Money.of(amount, "GBP", options);
    }
}

// usage
import { Money } from "./gbp_money"
```

**Comment by fire015** [comment]
Good idea thanks!
