### ISSUE TITLE
Methods `distribute`/`distributeBy` will not always distribute positive remainder to starting elements first

### ISSUE THREAD

**Issue by JstnMcBrd** [Dintero/money#222]
In the example for `Money.distribute()` and `Money.distributeBy()`, it shows that when there is a remainder, it will be equally distributed starting at the beginning of the array.

```js
/*
 * Example:
 * Money.of(10, 'NOK').distribute(3) => [3.34, 3.33, 3.33]
 *                                          ^ the remainder
 */
```

The implicit assumption is that remainders will be added to the beginning values in the array first, so the higher values will come first.

But this is only guaranteed when the rounding mode is `Big.roundDown`. In other situations, the divided value could be rounded up, and the remainder could be negative. Then it is **subtracted** from the beginning values in the array first, not **added**.

This is unintuitive behavior, because a remainder is usually a positive value left over from division, so users expect the first elements of the array that contain the remainder to be higher, not lower.

Here are two examples with different behavior:
```sh
> Money.of(10, 'NOK').distribute(3)
[3.34, 3.33, 3.33] # The highest values, the ones with the remainder, came first
> Money.of(11, 'NOK').distribute(3)
[3.66, 3.67, 3.67] # The highest values came last???
```

From the perspective of the user, it is not consistent whether the remainder will be distributed starting with the first or last elements in the array.

### Solutions

You could sort the array before returning it. Sorting can be slow with really large arrays, but usually money isn't distributed into too many parts.

Another solution could be to change the rounding mode to `Big.roundDown` when doing `distributeBy()` so the parts are always guaranteed to add up to less than the original value, if not evenly divisible. Then the remainder is always positive, and positive values get distributed to the beginning of the array first.

**Comment by frodeaa** [comment]
In this case we do not want to change the behaviour we should instead update the documentation to clarify the current behaviour
