### ISSUE TITLE
Money.of is not a function

### ISSUE THREAD

**Issue by davhaa15** [Dintero/money#50]
I am trying to use this to handle currency calculations in my node.js backend. I tried importing Money as follows:
const Money = require("@dintero/money");

Any time I try to use Money.of() as your examples show, I get the error Money.of is not a function. Am I missing something?

**Comment by frodeaa** [comment]
You need to access `Money` from the imported result

```js
const money = require("@dintero/money")
money.Money.of(123, "NOK")
```
